Repository wecode-bootcamp-korea/15-1st-DMFriends-backend, pull requests merged in 2020-12, with the labels that each got.

#6 [유하람] board models.py 필드 추가 및 크롤링 파일 삭제
  .DS_Store
  board/migrations/0003_auto_20201218_0906.py
  board/models.py
  web-crawling/.DS_Store
  web-crawling/category/.DS_Store
  web-crawling/category/category_all.csv
  web-crawling/category/category_all.py
  web-crawling/category/type.csv
  web-crawling/category/type.py
  web-crawling/character/.DS_Store
  web-crawling/character/character.csv
  web-crawling/character/character.py
  web-crawling/character/character_type.csv
  web-crawling/character/character_type.py
  web-crawling/character/seleniumCrawling.py
  web-crawling/main_today.csv
  web-crawling/main_today.py
  web-crawling/today.csv
Labels: Status: 리뷰 요청

#7 [우혁준] FIX: 회원가입 엔드포인트구현
  .DS_Store
  dmfriends/settings.py
  dmfriends/urls.py
  order/migrations/0003_auto_20201220_0420.py
  order/models.py
  product/migrations/0004_auto_20201220_0420.py
  product/models.py
  user/migrations/0002_auto_20201220_1632.py
  user/migrations/0003_auto_20201220_1645.py
  user/migrations/0004_auto_20201220_1656.py
  user/models.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#8 [이승연] Add: urls.py 및 views.py 작성 완료
  .vscode/settings.json
  dmfriends/settings.py
  dmfriends/urls.py
  images_db.uploader.py
  order/migrations/0003_auto_20201218_0644.py
  order/migrations/0004_auto_20201218_0647.py
  order/migrations/0005_auto_20201220_1600.py
  order/models.py
  order/urls.py
  order/views.py
  otherinfo_db.uploader.py
  product/migrations/0004_auto_20201218_0835.py
  product/migrations/0005_auto_20201219_1324.py
  product/urls.py
  product/views.py
  products_db.uploader.py
Labels: Status: Accepted

#9 [유하람] '오늘'탭 게시물 목록 조회 - 최신댓글 표출 ver.
  board/urls.py
  board/views.py
  dmfriends/settings.py
  dmfriends/urls.py
  user/urls.py
Labels: Status: 리뷰 요청

#10 [이승연] Add: 장바구니 엔드포인트 구현 완료
  board/migrations/0001_initial.py
  board/migrations/0002_auto_20201221_2327.py
  board/migrations/0003_auto_20201218_0906.py
  dmfriends/settings.py
  dmfriends/urls.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201221_2327.py
  order/migrations/0003_auto_20201218_0644.py
  order/migrations/0003_auto_20201220_0420.py
  order/migrations/0004_auto_20201218_0647.py
  order/migrations/0005_auto_20201220_1600.py
  order/models.py
  order/urls.py
  order/views.py
  otherinfo_db.uploader.py
  practice.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201221_2327.py
  product/migrations/0003_auto_20201217_1545.py
  product/migrations/0004_auto_20201218_0835.py
  product/migrations/0004_auto_20201220_0420.py
  product/migrations/0005_auto_20201219_1324.py
  product/urls.py
  product/views.py
  products_db.uploader.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201220_1632.py
  user/migrations/0003_auto_20201220_1645.py
  user/migrations/0004_auto_20201220_1656.py
Labels: Status: 리뷰 요청

#12 [우혁준] 이메일인증 및 추가 구현사항
  .DS_Store
  .gitignore
  board/.DS_Store
  board/migrations/0001_initial.py
  board/migrations/0002_auto_20201223_1835.py
  board/urls.py
  db_uploader.py
  dmfriends/settings.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201223_1835.py
  order/views.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201223_1835.py
  user/message.py
  user/migrations/0001_initial.py
  user/models.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#11 [유하람] 게시물 상세조회
  board/.DS_Store
  board/migrations/0001_initial.py
  board/migrations/0002_auto_20201223_2003.py
  board/urls.py
  board/views.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201223_2003.py
  order/models.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201223_2003.py
  user/migrations/0001_initial.py
  user/utils.py
Labels: Status: 리뷰 요청

#13 [이승연] Modify: 카트에 담긴 상품 반환 시 이미지 반환하도록 추가
  board/migrations/0001_initial.py
  board/migrations/0002_auto_20201224_0150.py
  board/views.py
  boarduser_db.uploader.py
  db_uploader.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201224_0150.py
  order/urls.py
  order/views.py
  otherinfo_db.uploader.py
  practice.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201224_0150.py
  product/views.py
  products_db.uploader.py
  requirements.txt
  rest_of_data_db_uploader.py
  user/migrations/0001_initial.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 수정 요청
